# Minimal stubs for the Sublime Text 4 API — only what sublime_agent_overview.py calls.
from typing import Any, Callable

HIDE_ON_MOUSE_MOVE_AWAY: int

class Settings:
    def get(self, key: str, default: Any = ...) -> Any: ...
    def set(self, key: str, value: Any) -> None: ...

class Edit: ...

class Region:
    def __init__(self, a: int, b: int = ...) -> None: ...
    def begin(self) -> int: ...

class Selection:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Region: ...
    def clear(self) -> None: ...
    def add(self, region: Region) -> None: ...

class View:
    def settings(self) -> Settings: ...
    def buffer_id(self) -> int: ...
    def name(self) -> str: ...
    def set_name(self, name: str) -> None: ...
    def set_scratch(self, scratch: bool) -> None: ...
    def size(self) -> int: ...
    def sel(self) -> Selection: ...
    def rowcol(self, point: int) -> tuple[int, int]: ...
    def text_point(self, row: int, col: int) -> int: ...
    def show(self, location: int) -> None: ...
    def viewport_position(self) -> tuple[float, float]: ...
    def set_viewport_position(self, xy: tuple[float, float], animate: bool = ...) -> None: ...
    def assign_syntax(self, syntax: str) -> None: ...
    def replace(self, edit: Edit, region: Region, text: str) -> None: ...
    def run_command(self, cmd: str, args: dict[str, Any] | None = ...) -> None: ...
    def set_read_only(self, value: bool) -> None: ...
    def window(self) -> Window | None: ...

class Window:
    def views(self) -> list[View]: ...
    def folders(self) -> list[str]: ...
    def set_project_data(self, data: dict[str, Any]) -> None: ...
    def new_file(self) -> View: ...
    def focus_view(self, view: View) -> None: ...
    def bring_to_front(self) -> None: ...
    def find_output_panel(self, name: str) -> View | None: ...
    def create_output_panel(self, name: str, unlisted: bool = ...) -> View: ...
    def run_command(self, cmd: str, args: dict[str, Any] | None = ...) -> None: ...
    def show_quick_panel(self, items: list[str], on_select: Callable[[int], None]) -> None: ...
    def status_message(self, msg: str) -> None: ...

def windows() -> list[Window]: ...
def active_window() -> Window: ...
def set_timeout(f: Callable[[], None], timeout_ms: int = ...) -> None: ...
def load_settings(base_name: str) -> Settings: ...
def status_message(msg: str) -> None: ...
def run_command(cmd: str, args: dict[str, Any] | None = ...) -> None: ...
